require("plateena.plugin.lsp.lspconfig")
require("plateena.plugin.lsp.null_ls")
require("plateena.plugin.lsp.mason")
require("plateena.plugin.lsp.lua")
require("plateena.plugin.lsp.emmet_ls")
require("plateena.plugin.lsp.php")
require("plateena.plugin.lsp.javascript")
require("plateena.plugin.lsp.json")
require("plateena.plugin.lsp.html")

