require("v2.config.lsp.lspconfig")
-- require("plateena.plugin.lsp.null_ls")
-- require("plateena.plugin.lsp.mason")
require("v2.config.lsp.lua")
-- require("plateena.plugin.lsp.emmet_ls")
-- require("plateena.plugin.lsp.php")
require("v2.config.lsp.javascript")
-- require("plateena.plugin.lsp.json")
-- require("plateena.plugin.lsp.html")
-- require("plateena.plugin.lsp.css")
-- require("plateena.plugin.lsp.tailwind")

